[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
bold = { family = "MonaspiceNe Nerd Font Mono", style = "Bold" }
italic = { family = "MonaspiceRn Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MonaspiceNe Nerd Font Mono", style = "Bold" }


offset = { x = 0, y = 8 }

[window]
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_padding = true

# Colors (Nordic)

[colors.primary]
background = '#191D24'
foreground = '#BBBDAF'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'
