import = [
    "~/.config/alacritty/themes/themes/nordic.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 0 }

[window]
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_padding = true
